### ISSUE TITLE
GUI/Wizard: Init repo and connect to repo wizard pages and communication to daemon

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#297]
The wizard is missing `sy connect` and `sy init` wizard pages. Implementing will require:
- [x] 1. Init/Connect: Wizard page for plugin configuration (dynamically generated on basis of plugin settings vs. XML-description of wizard page)
- [x] ~~2. Init/Connect: Wizard page for "testing repository" with test results~~ _Not necessary._
- [x] 3. Init: Wizard page for entering a new password (+ confirmation password)
- [x] 4. Connect: Wizard page for connecting via syncany:// link
- [x] 5. Connect: Wizard page for entering the existing password
- [x] 6. New request message + request handler: `InitWatchManagementRequest`
- [x] 7. New request message + request handler: `ConnectWatchManagementRequest`
- [x] 8. Figure out a concept how to implement `UserInteractionListener` via WebSocket (used during `InitOperation` and `ConnectOperation`!)
- [x] 9. Figure out how to handle plugin option callbacks. Only allow before/after-plugin callbacks? Force order? Discuss with others.
- [x] 10. Centralize duplicate code in `InitCommand` <-> `InitPanelController`
- [x] 11. `PluginSettingsPanel`: Validate fields individually _and_ alltogether. Highlight fields as invalid and make nicer error messages.
- [x] 13. `PluginSettingsPanel`: Allow non-string types in plugin text fields (File, int)
- [x] ~~14. Allow `boolean` types in plugin settings (= checkbox)~~ No use case yet.
- [x] 15. `File`: Differ between folder and file, allow file masks (e.g. via `@Setup(fileType = FileType.FILE, fileMask = "*.txt")`); Discuss with others.
- [x] ~~16. Centralize `warningImageLabel`, `warningMessageLabel`, `showWarning()` and `hideWarning()`~~ We can do this later.
- [x] 17. Disable GUI for plugins with nested settings (for now)
- [x] 18. Implement `@OAuth` annotation ([explanation see below](https://github.com/syncany/syncany/issues/297#issuecomment-67735562))
- [x] 19. Implement artificial OAuth token field ([explanation see below](https://github.com/syncany/syncany/issues/297#issuecomment-67735562))
- [x] 20. Implement invisible fields a la `@Setup(visible = false)` ([explanation see below](https://github.com/syncany/syncany/issues/297#issuecomment-67735562))
- [x] 21. Feedback on current code ([see below](https://github.com/syncany/syncany/issues/297#issuecomment-67793578))
- [ ] 22. Eliminate `onShowMessage` and `onUserNewPassword` in `UserInteractionListener` ([see below](https://github.com/syncany/syncany/issues/297#issuecomment-67793578))
- [x] 23. Discuss naming of the web socket messages ([see below](https://github.com/syncany/syncany/issues/297#issuecomment-67793578))
- [x] 24. Implement 4 "connect" screen flows ([see below](https://github.com/syncany/syncany/issues/297#issuecomment-67793578))
- [ ] 25. Remove "retry passwords" logic in ConnectOperation ([see below](https://github.com/syncany/syncany/issues/297#issuecomment-67793578))
- [x] 26. Test negative flows (wrong credentials, wrong password, rejecting a certificate, etc.)
- [x] 27. Focus first field per panel

**This issue is flagged as `prio:high` because it's one of the few things separating us from having a usable GUI. The above TODO items are updated with new items and checked when done.**
