### ISSUE TITLE
History browser: Multiple GUI/UX improvements

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#376]
A few leftovers and improvements from #333 that should be done eventually:
- [ ] "Preview" button on detail panel (= Restore to temp folder, then display), as per https://github.com/syncany/syncany/issues/333#issuecomment-72063585
- [ ] File entries in log view should be clickable and lead to the detailed file view (or at least offer a menu item to jump there); as per https://github.com/syncany/syncany/issues/333#issuecomment-69378208; prerequisite for this is #375.
- [ ] When not all tabs are loaded and the date slider is moves "too far" left (= not-yet-loaded date/tab), no tab is highlighted; and tabs are not loaded; we should load them; as per https://github.com/syncany/syncany/issues/333#issuecomment-71399058
